# Values to be expected from the laser. If they do not match, they will be adjusted internally.
# This serves as a quick check for the user.
scan_size: 300
angle_min: rad(-pi/2)
angle_max: rad(pi/2)
scan_time: 0.04
range_min: 0.001
range_max: 65.0
scan_frame: "scanner_laser"
